In [2]:
import json
from pathlib import Path
import pandas as pd


# Base paths 
from pathlib import Path

BASE_DIR = Path.cwd().parent  
DATA_DIR = BASE_DIR / "data"

csv_files = sorted(DATA_DIR.glob("nsf_grants_*.csv"))

print("Found CSV files:")
for f in csv_files:
    print("  -", f.name)

Found CSV files:
  - nsf_grants_2021.csv
  - nsf_grants_2022.csv
  - nsf_grants_2023.csv
  - nsf_grants_2024.csv
  - nsf_grants_2025.csv
  - nsf_grants_all_merged.csv
  - nsf_grants_all_mergeds.csv

In [3]:


# Find all yearly CSV files
csv_files = sorted(DATA_DIR.glob("nsf_grants_*.csv"))

merged_dfs = []  # Will store DataFrames for each year

for csv_path in csv_files:
    print(f"\nReading {csv_path.name} ...")

    # Extract year from filename, e.g. "nsf_grants_2021.csv" -> "2021"
    year = None
    try:
        year_str = csv_path.stem.split("_")[-1]
        if year_str.isnumeric():
            year = int(year_str)
    except Exception:
        pass

    if year is None:
        print(f"  Could not extract year from filename! Skipping {csv_path.name}")
        continue

    # Load one CSV
    df = pd.read_csv(csv_path)

    # Add year column
    df["year"] = year

    merged_dfs.append(df)

# Combine all DataFrames
print("\nMerging all years...")
df_all = pd.concat(merged_dfs, ignore_index=True)

# Save output
output_path = DATA_DIR / "nsf_grants_all_merged.csv"
df_all.to_csv(output_path, index=False)

Reading nsf_grants_2021.csv ...

Reading nsf_grants_2022.csv ...

Reading nsf_grants_2023.csv ...

Reading nsf_grants_2024.csv ...

Reading nsf_grants_2025.csv ...

Reading nsf_grants_all_merged.csv ...
  Could not extract year from filename! Skipping nsf_grants_all_merged.csv

Reading nsf_grants_all_mergeds.csv ...
  Could not extract year from filename! Skipping nsf_grants_all_mergeds.csv

Merging all years...

In [4]:
fil = pd.read_csv(DATA_DIR / "nsf_grants_all_merged.csv")

C:\Users\steff\AppData\Local\Temp\ipykernel_38456\3695564921.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  fil = pd.read_csv(DATA_DIR / "nsf_grants_all_merged.csv")

## Get the data and make dataframes for exercises

In [5]:
BASE_DIR = Path.cwd().parent   
DATA_DIR = BASE_DIR / "data"


excel_path = DATA_DIR / "nsf-grants-all-merged-csv.xls"


df = pd.read_excel(excel_path)


df.head()

,awd_id,awd_eff_date,awd_exp_date,year,awd_amount,dir_abbr,org_dir_long_name,div_abbr,org_div_long_name,cfda_num,inst_name,inst_state_code,n_pi,pgm_ele_codes,pgm_ele_names
0,1744844,2021-09-01,2026-08-31,2021,131876.0,GEO,Directorate for Geosciences,OPP,Office of Polar Programs (OPP),47.078,Berkeley Geochronology Center,CA,1,511200;511600,ANT Earth Sciences;ANT Glaciology
1,1744850,2021-09-01,2022-01-31,2021,125730.0,GEO,Directorate for Geosciences,OPP,Office of Polar Programs (OPP),47.078,Pacific Lutheran University,WA,1,511200;511600,ANT Earth Sciences;ANT Glaciology
2,1744865,2021-09-01,2026-08-31,2021,116342.0,GEO,Directorate for Geosciences,OPP,Office of Polar Programs (OPP),47.078,University of Maine,ME,1,511200;511600,ANT Earth Sciences;ANT Glaciology
3,1906383,2021-09-15,2027-08-31,2021,22222678.0,MPS,Directorate for Mathematical and Physical Scie...,DMR,Division Of Materials Research,"47.049, 47.083",Montana State University,MT,5,125300;915000,OFFICE OF MULTIDISCIPLINARY AC;EPSCoR Co-Funding
4,1910284,2021-10-01,2026-09-30,2021,484828.0,CSE,Directorate for Computer and Information Scien...,IIS,Division of Information & Intelligent Systems,47.070,University of Arkansas,AR,2,736400,Info Integration & Informatics

In [6]:
df.isnull().sum(), df.shape

(awd_id                 0
 awd_eff_date           0
 awd_exp_date           0
 year                   0
 awd_amount             5
 dir_abbr               0
 org_dir_long_name     14
 div_abbr               0
 org_div_long_name      5
 cfda_num              47
 inst_name              0
 inst_state_code       45
 n_pi                   0
 pgm_ele_codes        109
 pgm_ele_names        109
 dtype: int64,
 (44988, 15))

In [7]:
df_clean = df.dropna()
df_clean.isnull().sum(), df_clean.shape

(awd_id               0
 awd_eff_date         0
 awd_exp_date         0
 year                 0
 awd_amount           0
 dir_abbr             0
 org_dir_long_name    0
 div_abbr             0
 org_div_long_name    0
 cfda_num             0
 inst_name            0
 inst_state_code      0
 n_pi                 0
 pgm_ele_codes        0
 pgm_ele_names        0
 dtype: int64,
 (44819, 15))

In [8]:
excel_path = DATA_DIR / "output.csv"


df_output = pd.read_csv(excel_path)
df_output.head()

,grant_id,org_name,org_state,project_title,abstract,nsf_total_budget,status,reinstated,in_cruz_list,has_flagged_word,abscract
0,2201796,Carnegie-Mellon University,PA,Collaborative Research: Investigating Gender D...,Despite evidence that gender differences in ma...,1051218,0,False,True,True,Despite evidence that gender differences in ma...
1,2315095,University of Texas at San Antonio,TX,Rhetorical Engineering Education to Support Pr...,This project will provide a handbook of materi...,3641116,0,False,True,True,This project will provide a handbook of materi...
2,2236163,University of New Mexico,NM,"Increasing the Effectiveness of Justice, Equit...",This project aims to serve the national intere...,609429,0,False,True,True,This project aims to serve the national intere...
3,2243822,University of California-Berkeley,CA,NRT-HDR: Computational Research for Equity in ...,The criminal legal system is an important driv...,3000000,1,True,True,True,The criminal legal system is an important driv...
4,2216648,Oklahoma State University,OK,RaMP: Oklahoma Network addressing human impact...,Building a stronger and more diverse scientifi...,2719700,0,False,True,True,Building a stronger and more diverse scientifi...

In [9]:
excel_path = DATA_DIR / "output.csv"


df_output = pd.read_csv(excel_path)

df_output = df_output.rename(columns={"grant_id": "awd_id"})
df_output = df_output.rename(columns={"org_state": "state"})
df_clean = df.rename(columns={"inst_state_code": "state"})

df_clean["awd_id"] = df_clean["awd_id"].astype(str)
df_output["awd_id"] = df_output["awd_id"].astype(str)


df_merged = df_clean.merge(
    df_output[["awd_id", "status", "state"]],
    on="awd_id",
    how="left"
)

# Fill missing values → these grants were not terminated
df_merged["status"] = df_merged["status"].fillna(False)

df_merged.head()

,awd_id,awd_eff_date,awd_exp_date,year,awd_amount,dir_abbr,org_dir_long_name,div_abbr,org_div_long_name,cfda_num,inst_name,state_x,n_pi,pgm_ele_codes,pgm_ele_names,status,state_y
0,1744844,2021-09-01,2026-08-31,2021,131876.0,GEO,Directorate for Geosciences,OPP,Office of Polar Programs (OPP),47.078,Berkeley Geochronology Center,CA,1,511200;511600,ANT Earth Sciences;ANT Glaciology,False,NaN
1,1744850,2021-09-01,2022-01-31,2021,125730.0,GEO,Directorate for Geosciences,OPP,Office of Polar Programs (OPP),47.078,Pacific Lutheran University,WA,1,511200;511600,ANT Earth Sciences;ANT Glaciology,False,NaN
2,1744865,2021-09-01,2026-08-31,2021,116342.0,GEO,Directorate for Geosciences,OPP,Office of Polar Programs (OPP),47.078,University of Maine,ME,1,511200;511600,ANT Earth Sciences;ANT Glaciology,False,NaN
3,1906383,2021-09-15,2027-08-31,2021,22222678.0,MPS,Directorate for Mathematical and Physical Scie...,DMR,Division Of Materials Research,"47.049, 47.083",Montana State University,MT,5,125300;915000,OFFICE OF MULTIDISCIPLINARY AC;EPSCoR Co-Funding,False,NaN
4,1910284,2021-10-01,2026-09-30,2021,484828.0,CSE,Directorate for Computer and Information Scien...,IIS,Division of Information & Intelligent Systems,47.070,University of Arkansas,AR,2,736400,Info Integration & Informatics,False,NaN

In [10]:

df_merged["status"].unique(), df_merged["status"].value_counts()

(array([False, 1.0], dtype=object),
 status
 False    44632
 1.0        356
 Name: count, dtype: int64)

## Ex 1

In [11]:


state_year = (
    df_clean
    .groupby(["state", "year"], as_index=False)
    .agg(
        n_grants=("awd_id", "nunique"),
        total_amount=("awd_amount", "sum")
    )
)
# Map state abbreviation to full state name (needed for us_state_capitals lookup)
abbr2name = {
    'AL':'Alabama','AK':'Alaska','AZ':'Arizona','AR':'Arkansas','CA':'California','CO':'Colorado',
    'CT':'Connecticut','DE':'Delaware','FL':'Florida','GA':'Georgia','HI':'Hawaii','ID':'Idaho',
    'IL':'Illinois','IN':'Indiana','IA':'Iowa','KS':'Kansas','KY':'Kentucky','LA':'Louisiana',
    'ME':'Maine','MD':'Maryland','MA':'Massachusetts','MI':'Michigan','MN':'Minnesota','MS':'Mississippi',
    'MO':'Missouri','MT':'Montana','NE':'Nebraska','NV':'Nevada','NH':'New Hampshire','NJ':'New Jersey',
    'NM':'New Mexico','NY':'New York','NC':'North Carolina','ND':'North Dakota','OH':'Ohio','OK':'Oklahoma',
    'OR':'Oregon','PA':'Pennsylvania','RI':'Rhode Island','SC':'South Carolina','SD':'South Dakota',
    'TN':'Tennessee','TX':'Texas','UT':'Utah','VT':'Vermont','VA':'Virginia','WA':'Washington',
    'WV':'West Virginia','WI':'Wisconsin','WY':'Wyoming','DC':'District of Columbia'
}

state_year["state_name"] = state_year["state"].map(abbr2name)

In [12]:
import altair as alt
from vega_datasets import data

# Base map of the US
map_data = alt.topo_feature(data.us_10m.url, feature="states")

usChart = alt.Chart(map_data).mark_geoshape(
    fill="lightgray",
    stroke="white"
).properties(
    width=600,
    height=360
).project("albersUsa")

In [13]:
capitals = data.us_state_capitals.url

# Unique list of years for the dropdown
years = sorted(state_year["year"].dropna().unique().tolist())

# A dropdown selector for the year (this is like the interactions in your tutorial notebook)
year_dropdown = alt.binding_select(options=years, name="Year: ")

year_selection = alt.selection_point(
    fields=["year"],
    bind=year_dropdown
)
 # start with the latest year

points_base = alt.Chart(state_year, title="NSF Grants per State and Year"
).transform_lookup(
    lookup="state_name",
    from_=alt.LookupData(capitals, key="state", fields=["state", "lat", "lon"])
).transform_filter(
    alt.datum.lat != None
)

points = points_base.add_params(
    year_selection
).transform_filter(
    year_selection
).mark_circle(
    size=120,
    opacity=0.9,
    stroke="black",
    strokeWidth=0.6
).encode(
    longitude="lon:Q",
    latitude="lat:Q",
    color=alt.Color(
        "n_grants:Q",
        title="Number of grants",
        scale=alt.Scale(range=["#F1F4F7", "#B5D5DB", "#78B8C4", "#2F7F94"])
    ),
    tooltip=[
        alt.Tooltip("state_name:N", title="State"),
        alt.Tooltip("year:O", title="Year"),
        alt.Tooltip("n_grants:Q", title="# Grants"),
        alt.Tooltip("total_amount:Q", title="Total amount", format=",.0f")
    ]
)

chart_q1 = (usChart + points).configure_view(stroke=None)
chart_q1

alt.LayerChart(...)

In [24]:
import altair as alt
from vega_datasets import data

capitals = data.us_state_capitals.url

# Unique list of years for the dropdown
years = sorted(state_year["year"].dropna().unique().tolist())

year_dropdown = alt.binding_select(options=years, name="Year: ")
year_selection = alt.selection_point(
    fields=["year"],
    bind=year_dropdown,
    value={"year": years[-1]}   # start with latest year
)

# Base: state_year joined with capital lat/lon
base = alt.Chart(state_year, title="NSF Grants per State and Year"
).transform_lookup(
    lookup="state_name",    # column in state_year (e.g. "CA", "TX", ...)
    from_=alt.LookupData(
        capitals,
        key="state",        # column in capitals dataset
        fields=["state", "lat", "lon"]
    )
).transform_filter(
    alt.datum.lat != None
).add_params(
    year_selection
).transform_filter(
    year_selection
)

# --- bubble layer ---
bubbles = base.mark_circle(
    opacity=0.9,
    stroke="white",
    strokeWidth=0.7
).encode(
    x=alt.X("lon:Q", axis=None),
    y=alt.Y("lat:Q", axis=None),
    size=alt.Size(
        "n_grants:Q",
        title="# Grants",
        scale=alt.Scale(range=[100, 4000]),  # adjust to reduce overlap
        legend=None
    ),
    color=alt.Color(
        "n_grants:Q",
        title="Number of grants",
        scale=alt.Scale(range=["#F1F4F7", "#B5D5DB", "#78B8C4", "#2F7F94"])
    ),
    tooltip=[
        alt.Tooltip("state_name:N", title="State"),
        alt.Tooltip("year:O", title="Year"),
        alt.Tooltip("n_grants:Q", title="# Grants"),
        alt.Tooltip("total_amount:Q", title="Total amount", format=",.0f")
    ]
)

# --- text labels with state abbreviation ---
labels = base.mark_text(
    fontSize=11,
    fontWeight="bold",
    dy=3,           # small vertical shift to center text
    color="white"
).encode(
    x=alt.X("lon:Q", axis=None),
    y=alt.Y("lat:Q", axis=None),
    text="state:N"   # abbreviation from capitals (CA, TX, ...)
)

chart_q1 = (bubbles + labels).properties(
    width=800,
    height=500
).configure_view(
    stroke=None
)

chart_q1

alt.LayerChart(...)

In [15]:
years = sorted(state_year["year"].dropna().unique().tolist())
year_dropdown = alt.binding_select(options=years, name="Year: ") 
year_selection = alt.selection_point(fields=["year"], bind=year_dropdown)
bars_q1 = ( alt.Chart(state_year, title="Number of NSF Grants per State") 
           .add_params(year_selection) 
           .transform_filter(year_selection)
           .transform_window(
        rank="rank(n_grants)",
        sort=[alt.SortField("n_grants", order="descending")]
    )
    
    # 3) Keep only the top 10 states
    .transform_filter(alt.datum.rank <= 10)
           .mark_bar() 
           .encode( y=alt.Y("state:N", sort="-x", title="State"), 
                   x=alt.X("n_grants:Q", title="Grants"), 
                   color=alt.Color("n_grants:Q", title="Grants"), 
                   tooltip=[ alt.Tooltip("state_name:N", title="State"),  
                            alt.Tooltip("year:O", title="Year"), 
                            alt.Tooltip("n_grants:Q", title="Grants"),
                              alt.Tooltip("total_amount:Q", title="Total amount", format=",.0f") ] )
                                .properties(width=350, height=500) )
bars_q1

alt.Chart(...)

## Ex 2

In [16]:
import pandas as pd

dir_year = (
    df_clean
    .groupby(["dir_abbr", "org_dir_long_name", "year"], as_index=False)
    .agg(
        n_grants=("awd_id", "nunique"),
        total_amount=("awd_amount", "sum")
    )
)

In [17]:
import altair as alt

# Unique list of years for dropdown
years = sorted(dir_year["year"].dropna().unique().tolist())

# Year selection (Altair 5 style)
year_dropdown = alt.binding_select(options=years, name="Year: ")
year_sel = alt.selection_point(fields=["year"], bind=year_dropdown)

chart_q2 = (
    alt.Chart(dir_year, title="NSF Grants per Directorate")
    .add_params(year_sel)
    .transform_filter(year_sel)
    .mark_bar()
    .encode(
        x=alt.X("n_grants:Q", title="# Grants"),
        y=alt.Y(
            "org_dir_long_name:N",
            sort="-x",
            title="Directorate"
        )
      
        ,
        tooltip=[
            alt.Tooltip("org_dir_long_name:N", title="Directorate"),
            alt.Tooltip("dir_abbr:N", title="Abbr"),
            alt.Tooltip("year:O", title="Year"),
            alt.Tooltip("n_grants:Q", title="# Grants"),
            alt.Tooltip("total_amount:Q", title="Total amount", format=",.0f"),
        ]
    )
    .properties(width=450, height=300)
)

chart_q2

alt.Chart(...)

In [18]:
import altair as alt

# Selection that chooses the nearest year under the mouse
nearest = alt.selection_point(
    nearest=True,
    on='mouseover',
    fields=['year'],
    empty=False
)

# Base chart encoding (we'll reuse this in multiple layers)
base = alt.Chart(dir_year).encode(
    x=alt.X('year:O', title='Year'),
    y=alt.Y('n_grants:Q', title='# Grants'),
    color=alt.Color('org_dir_long_name:N', title='Directorate')
)

# 1) The main line for each directorate
line = base.mark_line().properties(
    width=800,   # wider plot like you asked
    height=400
)

# 2) Invisible selectors across the chart: capture the x (year) under the mouse
selectors = alt.Chart(dir_year).mark_point().encode(
    x='year:O',
    opacity=alt.value(0),
).add_params(
    nearest
)

# 3) Points on the lines, highlighted when nearest
points = base.mark_point().encode(
    opacity=alt.condition(nearest, alt.value(1), alt.value(0))
)

# 4) Text labels near the nearest points (show the total amount)
text = base.mark_text(align='left', dx=5, dy=-5).encode(
    text=alt.condition(nearest, 'n_grants:Q', alt.value(' '))
)

# 5) Vertical rule at the selected year
rules = alt.Chart(dir_year).mark_rule(color='gray').encode(
    x='year:O',
).transform_filter(
    nearest
)

chart_q2_line = alt.layer(
    line, selectors, points, rules, text
)

chart_q2_line

alt.LayerChart(...)

## Ex 3

In [19]:
import pandas as pd

dir_summary = (
    df_merged
    .groupby(["dir_abbr", "status"], as_index=False)
    .agg(
        n_grants=("awd_id", "nunique"),
        total_amount=("awd_amount", "sum")
    )
)
dir_summary

   dir_abbr status  n_grants  total_amount
0       BFA  False        13  2.377470e+06
1       BIO  False      4072  2.969902e+09
2       BIO    1.0        19  1.222448e+07
3       CSE  False      7253  3.920782e+09
4       CSE    1.0        66  3.076043e+07
5       EDU  False      4447  4.039740e+09
6       EDU    1.0        45  4.768447e+07
7       ENG  False      6446  2.889962e+09
8       ENG    1.0        37  1.999758e+07
9       GEO  False      5106  3.106718e+09
10      GEO    1.0        53  4.141757e+07
11      IRM  False        25  1.510515e+07
12      MPS  False      9804  4.902153e+09
13      MPS    1.0        86  4.037584e+07
14      NSB  False         9  3.933400e+05
15      O/D  False       941  9.750660e+08
16     OCIO  False         1  1.200000e+06
17      SBE  False      2857  8.352341e+08
18      SBE    1.0        38  1.339499e+07
19      TIP  False      3658  2.155136e+09
20      TIP    1.0        12  5.697220e+06

In [20]:
import altair as alt

chart_q3 = (
    alt.Chart(dir_summary, title="Cancelled vs Non-Cancelled Grants by Directorate")
    .mark_bar()
    .encode(
        x=alt.X("dir_abbr:N", title="Directorate"),
        y=alt.Y("n_grants:Q", title="# Grants"),
        color=alt.Color("status:N", title="Terminated?"),
        column=alt.Column("status:N", title="")
    )
    .properties(width=120, height=300)
)

chart_q3

alt.Chart(...)

## Ex 4

In [21]:
import pandas as pd

year_summary = (
    df_clean
    .groupby("year", as_index=False)
    .agg(
        total_amount=("awd_amount", "sum"),
        n_grants=("awd_id", "nunique")
    )
)

In [22]:
import altair as alt

# Selection that picks the nearest year under the mouse
nearest = alt.selection_point(
    nearest=True,
    on="mouseover",
    fields=["year"],
    empty=False
)

base = alt.Chart(year_summary).encode(
    x=alt.X("year:O", title="Year"),
    y=alt.Y("n_grants:Q", title="Number of Grants"),
)

# 1) Line of total funding
line_q4 = base.mark_line().properties(
    width=500,
    height=100,
    title="Total NSF Grant Amount Over the Years"
)

# 2) Invisible selectors across x to capture hover position
selectors_q4 = alt.Chart(year_summary).mark_point().encode(
    x="year:O",
    opacity=alt.value(0),
).add_params(
    nearest
)

# 3) Points on the line highlighted when nearest
points_q4 = base.mark_point().encode(
    opacity=alt.condition(nearest, alt.value(1), alt.value(0))
)

# 4) Text labels showing the amount for the selected year
text_q4 = base.mark_text(align="left", dx=5, dy=-5).encode(
    text=alt.condition(nearest, "n_grants:Q", alt.value(" "))
)

# 5) Vertical rule at the selected year
rules_q4 = alt.Chart(year_summary).mark_rule(color="gray").encode(
    x="year:O",
).transform_filter(
    nearest
)

chart_q4 = alt.layer(
    line_q4, selectors_q4, points_q4, rules_q4, text_q4
)
chart_q4

alt.LayerChart(...)

In [23]:
import altair as alt

# year_summary has: year, total_amount, n_grants
bar_q4 = (
    alt.Chart(year_summary, title="Total NSF Grant Amount Over the Years")
    .mark_bar()
    .encode(
        x=alt.X("year:O", title="Year"),
        y=alt.Y("n_grants:Q", title="Number of Grants"),
        tooltip=[
            alt.Tooltip("year:O", title="Year"),
            alt.Tooltip("total_amount:Q", title="Total amount", format=",.0f"),
            alt.Tooltip("n_grants:Q", title="# Grants"),
        ]
    )
    .properties(width=400, height=300)
)

bar_q4

alt.Chart(...)